version: 0.2

phases:
  build:	
    commands:
      - GOOS=linux GOARCH=amd64 go build -o main dilbert.go awkardyeti.go nedroid.go gofeed.go
  post_build:
    commands:
      - zip main.zip main

artifacts: 
  files: 
    - main.zip